version: '3'

services:
  frontend:
    build: ./vue-frontend/  # 指向前端项目的路径
    ports:
      - "8080:8080"  # 前端的端口

  backend:
    build: .  # 使用当前目录作为后端项目的路径
    ports:
      - "8080:8080"  # 后端的端口
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
